name: Spellcheck Task
on: [ push, pull_request ]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Get Changed Files
        id: files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            ./public/*.html
            ./public/*.txt
            ./public/*.json
            ./src/**/*.json
            ./src/**/*.ts
            ./src/**/*.tsx
      - name: Setup Node
        if: steps.files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Fetch Dependencies
        run: npm ci
      - name: Spell Check
        run: npm run spell-check --files ${{ steps.files.outputs.all_changed_files }}
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          path: ./build/spellcheck.json
      - name: Report
        uses: austenstone/spellchecker-cli-action-summary@main
        with:
          files-changed: ${{ steps.files.outputs.all_changed_files }}
